# Generated by Django 4.1.7 on 2023-05-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoilSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REQ_MODE', models.IntegerField()),
                ('REQ_COIL', models.CharField(blank=True, max_length=30, null=True)),
                ('REQ_LAST_COIL', models.CharField(blank=True, max_length=30, null=True)),
                ('REQ_SPARE1', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('READ_FLAG', models.BooleanField(default=False)),
            ],
        ),
    ]
