# Generated by Django 4.1.7 on 2023-05-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_client', '0002_coilschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoilRejectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REJ_COIL', models.CharField(max_length=100)),
                ('REJ_TYPE', models.CharField(max_length=30)),
                ('REJ_WEIGHT', models.FloatField()),
                ('REJ_SADDLE', models.CharField(max_length=30)),
                ('REJ_REASON', models.CharField(max_length=30)),
                ('REJ_COMMENT', models.CharField(max_length=30)),
                ('REJ_SPARE1', models.CharField(blank=True, max_length=30, null=True)),
                ('READ_FLAG', models.BooleanField(default=False)),
            ],
        ),
    ]
